# Generated by Django 3.2.9 on 2021-11-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='item_type',
            field=models.CharField(blank=True, choices=[('b', 'book'), ('m', 'magazine')], default='b', max_length=1, verbose_name='Type'),
        ),
    ]
