# Generated by Django 3.2.9 on 2021-12-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_author_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Genre'),
        ),
    ]
